### ISSUE TITLE
RabbitMQ 2.7.0 - rabbit_basic:delivery - unknown....

### ISSUE THREAD

**Issue by valkhyr** [squaremo/rabbitmq-lvc-plugin#3]
RabbitMQ 2.7.0 

rabbitmq-server-2.7.0/src/rabbit_basic.erl +95 - delivery/4
rabbit_exchange_type_lvc.erl +76 delivery/5
- Q, rabbit_basic:delivery(false, false, none, Msg, undefined))
- Q, rabbit_basic:delivery(false, false, Msg, undefined))

**Comment by squaremo** [comment]
API changed to remove transaction ID from rabbit_basic:delivery.
Fixed in commit 93f11697c7ee12edc4db00cd3c8885e175d2639d
