### ISSUE TITLE
plugin feature request or maybe help ...

### ISSUE THREAD

**Issue by valkhyr** [squaremo/rabbitmq-lvc-plugin#4]
It is not issue! It is feature request.

Can we use topic exchange too. Currently plugin uses direct but for example i need to get last values based on certain routing keys like test.*

Is it possible to implement this extra feature: 

When a message arrives in queue - check mnesia DB if previous message is same like current message. If "yes" then do not notify and do not flood subscribers with same data. Can you give me some directions .. or code.., .. or advice... ?

**Comment by squaremo** [comment]
> Can we use topic exchange too. Currently plugin uses direct but for example i need to get last values based on certain 
> routing keys like test.*

This is a lot trickier than using direct routing. Why? Because binding keys aren't known in advance, and a binding key may match many messages.

Consider this situation: a consumer binds to a last-value topic exchange with key "_.nyse._". The exchange has to decide which is the last of all the messages to date matching that key. Now, the exchange might keep a buffer of all messages and simply go backwards until it hits one that matches; but this buffer would have to be unbounded to satisfy the LVC semantics. With the direct routing the values are at least bounded by the set of routing keys used in messages.

**Comment by valkhyr** [comment]
All messages matching that key gonna be last and unique based on their routing key. In this case, i can have consumer who is listening on "test.*" and many publishers "test.1", "test.X". If the state of "test.X" changes then the consumer would like to know. If the consumer comes online for a first time he wants to know the state/msg of all subscribers in "test.X". I'm not sure how to implement this logic with only direct exchange, because i have like 10K+ objects :( I am kinda new to erlang and RabbitMQ.

**Comment by squaremo** [comment]
So it would be fine for the consumer, upon binding, to receive potentially 10K+ messages with matching but distinct keys?

**Comment by valkhyr** [comment]
I'm not sure how fine it is, but is one possible solution. I need last state of many objects, next i have to start listening for changed states. Routing key is the name of my object. I do not need high performance at initialization. Or in other words i would like to move part of my logic into RabbitMQ. Using this addon like this, we can describe for example "state machines". I'm new to erlang and RabbitMQ, but i'm almost sure they can do the job perfectly.

**Comment by squaremo** [comment]
Another way to do this might be to have a "state server", or servers, that listen for an incoming request then respond with their serialised state (all at once, if the server is keeping track of many object states). The trick of course is to be able to synchronise that whole state response with the updates coming through.

Have a look at http://zguide.zeromq.org/page:all#A-Shared-Key-Value-Cache-Clone-Pattern

**Comment by valkhyr** [comment]
Question: Is it possible to trigger "route" in the middle of "add_binding" or before ? Or in other words when consumer binds and someone meanwhile is trying to route message will this message wait in the queue while "add_bind" process is over ?

btw thanks for the link

**Comment by squaremo** [comment]
Exchanges are in general racy; that is, only events from a single channel will be serialised, and routing may be done while other operations are in progress.

**Comment by valkhyr** [comment]
thanks for the help
